site_name: ROMS Communication Toolbox (romscom) Docs

theme:
  name: "material"
  features:
    - content.footnote.tooltips


plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]

nav:
  - index.md
  - About: explanation.md
  - Getting Started: installation.md
  - Examples: examples.md
  - "Reference: romscom": reference_romscom.md
  - "Reference: rcutils": reference_rcutils.md

markdown_extensions:
  - tables
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

